package com.campusconnect.neo4j.types.common;


public enum AuditEventType {
    FOLLOWING,
    FRIEND,
    BORROWED,
    WISHLIST,
    USER_CREATED,
    USER_UPDATED,
    UPDATED_ADDRESS,
    ADDED_ADDRESS, FOLLOWED, LENT,
    BORROW_REJECTED,
    BORROW_INITIATED,
    BORROW_AGREED,
    REMINDER_SENT, DELETED_ADDRESS
}
